// src/shared/errors/error-codes.ts

export const ERROR_CODES = {
	// General
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	CONFLICT: "CONFLICT",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

	// Authentication
	AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	SESSION_EXPIRED: "SESSION_EXPIRED",

	// Authorisation
	INSUFFICIENT_PERMISSION: "INSUFFICIENT_PERMISSION",
	INSUFFICIENT_HOUSEHOLD_PERMISSION: "INSUFFICIENT_HOUSEHOLD_PERMISSION",

	// Households
	HOUSEHOLD_NOT_FOUND: "HOUSEHOLD_NOT_FOUND",
	HOUSEHOLD_ID_REQUIRED: "HOUSEHOLD_ID_REQUIRED",
	HOUSEHOLD_ALREADY_EXISTS: "HOUSEHOLD_ALREADY_EXISTS",
	HOUSEHOLD_ORGANIZATION_CREATION_FAILED:
		"HOUSEHOLD_ORGANIZATION_CREATION_FAILED",
	HOUSEHOLD_CREATION_FAILED: "HOUSEHOLD_CREATION_FAILED",

	// Household members
	HOUSEHOLD_MEMBER_NOT_FOUND: "HOUSEHOLD_MEMBER_NOT_FOUND",
	HOUSEHOLD_MEMBER_CONFLICT: "HOUSEHOLD_MEMBER_CONFLICT",
	HOUSEHOLD_CLAIMANT_LIMIT_REACHED: "HOUSEHOLD_CLAIMANT_LIMIT_REACHED",
	HOUSEHOLD_SELF_MEMBER_EXISTS: "HOUSEHOLD_SELF_MEMBER_EXISTS",
	HOUSEHOLD_PARTNER_EXISTS: "HOUSEHOLD_PARTNER_EXISTS",
	AUTH_USER_ALREADY_LINKED: "AUTH_USER_ALREADY_LINKED",

	// Income
	INCOME_SOURCE_NOT_FOUND: "INCOME_SOURCE_NOT_FOUND",
	INCOME_SOURCE_CONFLICT: "INCOME_SOURCE_CONFLICT",

	// Expenses
	EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
	EXPENSE_CONFLICT: "EXPENSE_CONFLICT",

	// Debts
	DEBT_NOT_FOUND: "DEBT_NOT_FOUND",
	DEBT_PAYMENT_NOT_FOUND: "DEBT_PAYMENT_NOT_FOUND",
	DEBT_CONFLICT: "DEBT_CONFLICT",

	// Calculations
	CALCULATION_NOT_FOUND: "CALCULATION_NOT_FOUND",
	CALCULATION_FAILED: "CALCULATION_FAILED",
	RULE_SET_NOT_FOUND: "RULE_SET_NOT_FOUND",
	UNSUPPORTED_TAX_YEAR: "UNSUPPORTED_TAX_YEAR",

	// Money and frequency
	INVALID_MONEY_AMOUNT: "INVALID_MONEY_AMOUNT",
	INVALID_PERCENTAGE: "INVALID_PERCENTAGE",
	INVALID_PAYMENT_FREQUENCY: "INVALID_PAYMENT_FREQUENCY",

	// Date ranges
	INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
	INVALID_TAX_YEAR: "INVALID_TAX_YEAR",
	INVALID_ASSESSMENT_PERIOD: "INVALID_ASSESSMENT_PERIOD",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function isErrorCode(value: unknown): value is ErrorCode {
	return (
		typeof value === "string" &&
		Object.values(ERROR_CODES).includes(value as ErrorCode)
	);
}
